-- MySQL Script generated by MySQL Workbench
-- Sun Jan 29 04:38:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weatheralerts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weatheralerts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weatheralerts` DEFAULT CHARACTER SET utf8 ;
USE `weatheralerts` ;

-- -----------------------------------------------------
-- Table `weatheralerts`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weatheralerts`.`User` (
  `id` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contact_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weatheralerts`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weatheralerts`.`Location` (
  `id` INT NOT NULL,
  `cityName` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cityName_UNIQUE` (`cityName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weatheralerts`.`NotificationType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weatheralerts`.`NotificationType` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weatheralerts`.`AlertPreference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weatheralerts`.`AlertPreference` (
  `idPreference` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `lower_threshold` FLOAT NOT NULL,
  `higher_threshold` FLOAT NOT NULL,
  `User_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `NotificationType_id` INT NOT NULL,
  PRIMARY KEY (`idPreference`),
  INDEX `fk_Preference_User_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk__location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_AlertPreference_NotificationType1_idx` (`NotificationType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Preference_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `weatheralerts`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `weatheralerts`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlertPreference_NotificationType1`
    FOREIGN KEY (`NotificationType_id`)
    REFERENCES `weatheralerts`.`NotificationType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weatheralerts`.`Temperature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weatheralerts`.`Temperature` (
  `idTemperature` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `tempCelcius` FLOAT NOT NULL,
  `location_id` INT NOT NULL,
  `tempFahrenheit` FLOAT NULL,
  PRIMARY KEY (`idTemperature`),
  INDEX `fk_Temperature_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_Temperature_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `weatheralerts`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
